name: Build and Release Docker Images
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the linux x64 binaries 
        required: true
        type: string
jobs:
  build_and_release_all_docker_images:
    strategy:
      max-parallel: 1
      matrix:
        environment: 
          - name: chrome
            version: 117.0
          - name: android
            version: 13.0
    uses: ./.github/workflows/docker-images-base-workflow.yml
    with:
      version: "${{ inputs.version }}"
      environment_name: ${{ matrix.environment.name }}
      environment_version: ${{ matrix.environment.version}}
    secrets: inherit