name: Check and Build Latest From Dockerhub
on: workflow_dispatch

env:
  DOCKER_REPOSITORY: askui-docker-images-repository-playground
  ASKUI_VERSION: 0.13.1

jobs:
  check_latest_selenium_chrome_tags:
    name: Get latest selenium chrome tags
    runs-on: [ubuntu-latest]
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: set-matrix
        run: |
          curl -sL https://hub.docker.com/v2/repositories/selenium/standalone-chrome/tags\?page_size\=100 | jq -r '.results[] | select(.name | contains(".")) | .name | if contains("-") then split("-")[1] else . end | select(. | contains("."))' | sort -V -r -u | grep -Ev '(dev|latest|beta|for)' > tags.conf
          JSON=$(while IFS= read -r line; do
                            docker manifest inspect askuigmbh/${{ env.DOCKER_REPOSITORY }}:${{ env.ASKUI_VERSION }}-chrome-${{ version }}-amd64
                            if [ $? -ne 0 ]; then
                              jq -n --arg version $line '{"askui":"0.13.1","name":"chrome","version":$version}'
                            fi
                            done < "tags.conf" | jq -s .)
          JSON_STRING=$( jq -n --argjson json "$JSON" '$json')
          echo $JSON_STRING
          JSON_COMPACT=$(echo $JSON_STRING | jq -c .)
          echo "matrix={\"include\":$JSON_COMPACT}" >> $GITHUB_OUTPUT
  build_and_release_all_docker_images:
    needs: check_latest_selenium_chrome_tags
    strategy:
      max-parallel: 1
      matrix: ${{ fromJSON(needs.check_latest_selenium_chrome_tags.outputs.matrix) }}
    uses: ./.github/workflows/docker-images-base-workflow.yml
    with:
      version: ${{ matrix.askui }}
      environment_name: ${{ matrix.name }} ## usually chrome
      environment_version: ${{ matrix.version }} ## chrome version
    secrets: inherit

