name: Check and Build Latest From Dockerhub
on: workflow_dispatch

env:
  DOCKER_REPOSITORY: askui-docker-images-repository-playground

jobs:
  check_latest_selenium_chrome_tags:
    name: Get latest selenium chrome tags
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: curl -sL https://hub.docker.com/v2/repositories/selenium/standalone-chrome/tags\?page_size\=100 | jq -r '.results[] | select(.name | contains(".")) | .name | if contains("-") then split("-")[1] else . end | select(. | contains("."))' | sort -V -r -u | grep -Ev '(dev|latest|beta|for)' > tags.conf
      - run: echo tags.conf
      - run: >
             JSON=$(while IFS= read -r line; do
                               jq -n --arg version $line '{"name":"chrome", "version":$version}'
                               done < "tags.conf" | jq -s .)
             echo $JSON | jq '.[]'
             JSON_STRING=$( jq -n --argjson json "$JSON" '$json')
             echo $JSON_STRING
      # TODO check for existence of image
      # - run: docker manifest inspect askuigmbh/${{ env.DOCKER_REPOSITORY }}:129.0
      - id: set-matrix
        run: echo "MATRIX_CONFIG={\"include\":$JSON_STRING" >> $GITHUB_OUTPUT
  # build_and_release_all_docker_images:
  #   env:
  #     MATRIX: ${{fromJson(steps.set-matrix.outputs.MATRIX_CONFIG)}}
  #   strategy:
  #     max-parallel: 1
  #     matrix: ${{MATRIX}}
  #       TODO remove this
  #       environment: 
  #         - name: chrome
  #           version: 117.0
  #   uses: ./.github/docker-images-base-workflow.yml
  #   with:
  #     version: ${{ inputs.version }} ## askui version
  #     environment_name: ${{ matrix.name }} ## usually chrome
  #     environment_version: ${{ matrix.version }} ## chrome version
  #   secrets: inherit

