name: Check and Build Latest From Dockerhub
on: 
  workflow_dispatch:
  schedule:
    - cron:  '59 23 * * *'

env:
  DOCKER_REPOSITORY: askui-ui-controller
  ASKUI_SUITE_VERSION: 24.12.1

jobs:
  check_latest_selenium_chrome_tags:
    name: Get latest selenium chrome tags
    runs-on: [ubuntu-latest]
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}
      status: ${{steps.set-matrix.outputs.status}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: set-matrix
        run: |
          curl -sL https://hub.docker.com/v2/repositories/selenium/standalone-chrome/tags\?page_size\=100 | jq -r '.results[] | select(.name | contains(".")) | .name | if contains("-") then split("-")[0] else . end | select(. | contains(".")) | select(. | startswith("4") | not)' | sort -V -r -u | grep -Ev '(dev|latest|beta|for)' > tags.conf
          JSON=$(while IFS= read -r line; do
                            docker manifest inspect askuigmbh/${{ env.DOCKER_REPOSITORY }}:${{ env.ASKUI_SUITE_VERSION }}-chrome-${line}-amd64 > /dev/null 2>&1
                            if [ $? -ne 0 ]; then
                              jq -n --arg controllerversion "${{ env.ASKUI_SUITE_VERSION }}" --arg version $line '{"askuicontroller":$controllerversion,"name":"chrome","version":$version,"tag":"\($controllerversion)-chrome-\($version)-amd64"}'
                            fi
                            done < "tags.conf" | jq -s .)
          JSON_STRING=$( jq -n --argjson json "$JSON" '$json')
          echo $JSON_STRING
          if [[ "$JSON_STRING" == "[]" ]]; then
            echo "status=donothing" >> $GITHUB_OUTPUT
          else
            echo "status=doit" >> $GITHUB_OUTPUT
            # Duplicate the first entry and tag it with latest
            JSON_COMPACT=$(echo $JSON_STRING | jq -c '[.[0]] + .[0:] | .[0].tag = "latest"')
            echo "matrix={\"include\":$JSON_COMPACT}" >> $GITHUB_OUTPUT
          fi
  build_and_release_all_docker_images:
    needs: check_latest_selenium_chrome_tags
    if: ${{ !contains(needs.check_latest_selenium_chrome_tags.outputs.status, 'donothing') }}
    strategy:
      max-parallel: 1
      matrix: ${{ fromJSON(needs.check_latest_selenium_chrome_tags.outputs.matrix) }}
    uses: ./.github/workflows/docker-images-base-workflow.yml
    with:
      askui_suite_version: ${{ matrix.askuicontroller }}
      environment_name: ${{ matrix.name }} ## usually chrome
      environment_version: ${{ matrix.version }} ## chrome version
      tag: ${{ matrix.tag }}
    secrets: inherit

